### ISSUE TITLE
data load

### ISSUE THREAD

**Issue by Secret-kite** [Reza-Asiyabi/Complex-Valued-End-to-End-Deep-Network-for-SAR#2] opened 2024-11-28 09:32 UTC
In case1,I used np.stack to merge the hh and hv data, changing the number of channels to 2, but after starting the training, an error was reported as photo.
<img width="1145" alt="1732786232452" src="https://github.com/user-attachments/assets/635eefd0-0fab-4bbe-b9d3-e197bf26f8c6">
Is this the correct way to handle data input? If it is correct, how should I modify the code to fix the error?

**Comment by Reza-Asiyabi** [comment] 2024-11-28 10:11
As it is mentioned in the error, the network expects 3D or 4D input in the form of (batch size x channels x height x width) but your input has two extra dimensions in the beginning. These extra dimensions might have created because sometimes when the batch size or number of the channels are one, an extra dimension is added to satisfy the required input data format, but it is not the case here. Get rid of those extra dimensions in your input and I believe it will resolve your issue.

I'm closing the issue but feel free to reopen it if the problem isn't solved.

**Closed as completed by Reza-Asiyabi** 2024-11-28 10:11 UTC
